// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practice.Data.Context;

#nullable disable

namespace Practice.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("LessonStudent", b =>
                {
                    b.Property<int>("LessonsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LessonsId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("LessonStudent");
                });

            modelBuilder.Entity("Practice.Entity.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActice = true,
                            LessonName = "Matematik"
                        },
                        new
                        {
                            Id = 2,
                            IsActice = true,
                            LessonName = "Turkce"
                        },
                        new
                        {
                            Id = 3,
                            IsActice = true,
                            LessonName = "Fizik"
                        },
                        new
                        {
                            Id = 4,
                            IsActice = true,
                            LessonName = "Kimya"
                        });
                });

            modelBuilder.Entity("Practice.Entity.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchoolNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Abc",
                            IsActice = true,
                            LastName = "Kartal",
                            SchoolNumber = 297
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Def",
                            IsActice = true,
                            LastName = "Koc",
                            SchoolNumber = 704
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Ghi",
                            IsActice = true,
                            LastName = "Aslan",
                            SchoolNumber = 514
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Ijk",
                            IsActice = true,
                            LastName = "Kaplan",
                            SchoolNumber = 115
                        });
                });

            modelBuilder.Entity("LessonStudent", b =>
                {
                    b.HasOne("Practice.Entity.Entities.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Practice.Entity.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
